In [1]:
import numpy as np
import util

In [2]:
from dynamics import *


In [3]:
from util import compute_pairwise_distance_nd_Sym

In [19]:
n_quads = 3
radius=  0.5

In [20]:
x0,xr = util.setup_n_quads_V2(n_quads, 2*radius)

positions retrieved
positions retrieved


In [21]:
x0.shape, xr.shape

((36, 1), (36, 1))

In [22]:
x1 = np.array([[0,0,0,0,0,0, 1,1,1,0,0,0]])
dist = compute_pairwise_distance_nd_Sym(x1,[6,6],[3])

In [23]:
nu = 4*3

In [24]:
x_curr = x0
u_curr = np.zeros((nu, 1))

In [27]:
util.distance_to_goal(x_curr.flatten(), xr.flatten(), 3, 12)

array([2.49197001, 2.81364247, 1.06386811])

In [7]:
dist

[]

In [2]:
# x0, xr = util.setup_n_quads(100)

In [16]:
util.compute_pairwise_distance(x0,[6]*100,3).min()

0.6724921125961261

In [17]:
util.compute_pairwise_distance(x0,[6]*100,3).max()

28.129509680658373

In [6]:
ids = [100+n for n in range(3)]

In [7]:
graph = util.define_inter_graph_threshold(x0,0.3,[6,6,6],ids)

In [8]:
graph.items()

dict_items([(100, [100, 102]), (101, [101, 102]), (102, [100, 101, 102])])

In [13]:
for i,j in graph.items():
    # print(i,j)
    print(i, j.index(i))

100 0
101 0
102 2


In [4]:
x_curr = x0

In [5]:
x0.shape

(18, 1)

In [16]:
u_curr = np.random.rand(9,1)

In [25]:
u_curr.shape

(9, 1)

In [29]:
np.zeros((9,1)).shape

(9, 1)

In [17]:
A,B  = linear_kinodynamics(0.1,3)

In [18]:
trj = forward_pass(A,B,10,x_curr,u_curr)

In [30]:
trj.shape

(18, 11)

In [24]:
forward_pass(A[0:6,0:6],B[0:6,0:3],10,x_curr[0:6],u_curr[0:3])

array([[5.00000000e-01, 5.00504266e-01, 5.10589596e-01, 5.30255990e-01,
        5.59503447e-01, 5.98331967e-01, 6.46741550e-01, 7.04732197e-01,
        7.72303908e-01, 8.49456682e-01, 9.36190519e-01],
       [1.50000000e+00, 1.50044922e+00, 1.50943355e+00, 1.52695301e+00,
        1.55300759e+00, 1.58759729e+00, 1.63072211e+00, 1.68238205e+00,
        1.74257711e+00, 1.81130729e+00, 1.88857259e+00],
       [1.00000000e+00, 1.00000462e+00, 1.00009706e+00, 1.00027731e+00,
        1.00054537e+00, 1.00090124e+00, 1.00134493e+00, 1.00187644e+00,
        1.00249575e+00, 1.00320288e+00, 1.00399783e+00],
       [0.00000000e+00, 9.58106343e-02, 1.91621269e-01, 2.87431903e-01,
        3.83242537e-01, 4.79053171e-01, 5.74863806e-01, 6.70674440e-01,
        7.66485074e-01, 8.62295708e-01, 9.58106343e-01],
       [0.00000000e+00, 8.53512054e-02, 1.70702411e-01, 2.56053616e-01,
        3.41404822e-01, 4.26756027e-01, 5.12107233e-01, 5.97458438e-01,
        6.82809643e-01, 7.68160849e-01, 8.53512054e-

In [19]:
trj[:,0]

array([0.5, 1.5, 1. , 0. , 0. , 0. , 2.5, 1.5, 1. , 0. , 0. , 0. , 1.5,
       1.3, 1. , 0. , 0. , 0. ])

In [20]:
trj[:,1]

array([5.00504266e-01, 1.50044922e+00, 1.00000462e+00, 9.58106343e-02,
       8.53512054e-02, 8.78135150e-04, 2.50028277e+00, 1.50050089e+00,
       1.00012996e+00, 5.37272443e-02, 9.51686844e-02, 2.46932765e-02,
       1.50008152e+00, 1.30015044e+00, 1.00014940e+00, 1.54879327e-02,
       2.85829957e-02, 2.83851275e-02])

In [21]:
trj[:,2]

array([5.10589596e-01, 1.50943355e+00, 1.00009706e+00, 1.91621269e-01,
       1.70702411e-01, 1.75627030e-03, 2.50593827e+00, 1.51051864e+00,
       1.00272926e+00, 1.07454489e-01, 1.90337369e-01, 4.93865530e-02,
       1.50171182e+00, 1.30315917e+00, 1.00313730e+00, 3.09758655e-02,
       5.71659914e-02, 5.67702551e-02])

In [22]:
trj[:,3]

array([0.53025599, 1.52695301, 1.00027731, 0.2874319 , 0.25605362,
       0.00263441, 2.5169665 , 1.53005327, 1.00779788, 0.16118173,
       0.28550605, 0.07407983, 1.50489093, 1.30902621, 1.00896372,
       0.0464638 , 0.08574899, 0.08515538])